# Generated by Django 5.1.5 on 2025-02-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
