# Generated by Django 5.1.5 on 2025-02-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0003_form_votings_choice_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form_votings',
            new_name='Votings',
        ),
    ]
