# Generated by Django 5.1.5 on 2025-02-23 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0004_rename_form_votings_votings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votings',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='votings',
            name='pub_date',
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='votings',
            name='survey_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_id', to='django_site.survey'),
        ),
    ]
