# Generated by Django 5.1.5 on 2025-02-23 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0005_remove_votings_created_by_remove_votings_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='survey_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='survey_id', to='django_site.survey'),
            preserve_default=False,
        ),
    ]
