# Generated by Django 5.1.5 on 2025-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site', '0006_alter_votings_survey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
